apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: toggle-master
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 539412416767.dkr.ecr.us-east-1.amazonaws.com/analytics-service:0fff4762a5d794578993e50d08231936269799a3
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: PORT
              value: "8005"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_DYNAMODB_TABLE
              value: "ToggleMasterAnalytics"
            - name: AWS_SQS_URL
              value: "https://sqs.us-east-1.amazonaws.com/539412416767/togglemaster-queue"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"