{
 "title": "ToggleMaster - Observability",
 "panels": [
  {
   "title": "CPU por Pod",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"toggle-master\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memória por Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"toggle-master\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logs em tempo real",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{namespace=\"toggle-master\"}"
    }
   ]
  }
 ]
}