apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: toggle-master
  labels:
    app: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 539412416767.dkr.ecr.us-east-1.amazonaws.com/targeting-service:ce6d37fac3b70302576d59067782278e4a1ec8a2
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@togglemaster-targeting-db.c3quisgw2evv.us-east-1.rds.amazonaws.com:5432/authdb?sslmode=disable"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "targetingdb"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: DB_PASSWORD
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8001"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"