apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: toggle-master
  labels:
    app: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/targeting-service:initial
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: DB_HOST
              value: "SEU_RDS_TARGETING_ENDPOINT"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "targetingdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "SUA_SENHA_AQUI"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"