apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: toggle-master
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 539412416767.dkr.ecr.us-east-1.amazonaws.com/auth-service:fdb9b8283f013493749097a41b1bd050575bc887
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: MASTER_KEY
              value: "admin-secreto-123"
            - name: DB_HOST
              value: "togglemaster-auth-db.c3quisgw2evv.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "authdb"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_PASSWORD
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"