apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-external-secret
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: togglemaster/auth-db-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: togglemaster/auth-db-credentials
        property: password