apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - auth-service-app.yaml
  - flag-service-app.yaml
  - targeting-service-app.yaml
  - evaluation-service-app.yaml
  - analytics-service-app.yaml