apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flag-service-external-secret
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: flag-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: togglemaster/flag-db-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: togglemaster/flag-db-credentials
        property: password