apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: toggle-master
  labels:
    app: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 539412416767.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:619a219423c7d43ccb643ffd58f611bb80d842c4
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              value: "8004"
            - name: REDIS_URL
              value: "togglemaster-cache.dttbjt.0001.use1.cache.amazonaws.com"
            - name: REDIS_PORT
              value: "6379"
            - name: AWS_SQS_URL
              value: "https://sqs.us-east-1.amazonaws.com/539412416767/togglemaster-queue"
            - name: AWS_REGION
              value: "us-east-1"
            - name: FLAG_SERVICE_URL
              value: "http://flag-service:8002"
            - name: TARGETING_SERVICE_URL
              value: "http://targeting-service:8003"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"